### ISSUE TITLE
Error in bower_install

### ISSUE THREAD

**Issue by prasadmc** [nvbn/django-bower#9]
Hi,
I am trying to run bower_install and I am getting following error
D:\django\mysite>python manage.py bower_install
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 242, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 285, in execute
    output = self.handle(_args, *_options)
  File "C:\Python27\lib\site-packages\djangobower\management\commands\bower_install.py", line 11, in handle
    bower_adapter.install(settings.BOWER_INSTALLED_APPS, *args)
  File "C:\Python27\lib\site-packages\djangobower\bower.py", line 32, in install
    cwd=self._components_root,
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

I have latest version of Node.js (0.10.24), npm (1.3.21), Django (1.6.1) and bower (1.2.8)

Can you pls help resolve the problem?

**Comment by bossajie** [comment]
what did you do? I am still getting this error
